[package]
name = "socks5rs"
description = "Minimal, Low-Level and simple socks5 protocol implementation"
version = "0.1.2"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "server"
