[package]
name = "socks5rs"
description = "Minimal, Low-Level and simple socks5 protocol implementation"
version = "0.1.2"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/thehxdev/socks5rs"

[lib]
crate-type = ["lib"]

[dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "server"
